# Generated by Django 3.1 on 2020-08-27 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='DateTime on wich the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='DateTime on wich the object was last modiefed', verbose_name='modified at')),
                ('name', models.CharField(max_length=140, verbose_name='Nombre De Máquina')),
                ('serial_number', models.SlugField(max_length=140, unique=True, verbose_name='Número de serie')),
                ('model', models.CharField(max_length=140, verbose_name='Modelo')),
                ('about', models.CharField(max_length=255, verbose_name='Descripción De Máquina')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='machine/picture', verbose_name='Imagen')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='DateTime on wich the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='DateTime on wich the object was last modiefed', verbose_name='modified at')),
                ('name', models.CharField(max_length=140, verbose_name='Nombre del Manual')),
                ('file', models.FileField(upload_to='', verbose_name='Pdf Manual')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='DateTime on wich the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='DateTime on wich the object was last modiefed', verbose_name='modified at')),
                ('is_active', models.BooleanField(default=True, help_text='Only active user ar allowed to interact with the machine', verbose_name='Es Activo')),
                ('is_owner', models.BooleanField(default=False, help_text='Machine admin can see you detail', verbose_name='Es Propietario de la máquina')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
