# Generated by Django 3.1 on 2020-08-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20200805_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='about',
            field=models.CharField(max_length=255, verbose_name='Descripción De Máquina'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model',
            field=models.CharField(max_length=140, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Nombre De Máquina'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='next_service',
            field=models.DateTimeField(verbose_name='Proximo servicio'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='machine/picture', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serial_number',
            field=models.SlugField(max_length=140, unique=True, verbose_name='Número de serie'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active user ar allowed to interact with the machine', verbose_name='Es Activo'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Machine admin can see you detail', verbose_name='Es Propietario de la máquina'),
        ),
    ]
