# Generated by Django 3.1 on 2020-08-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20200826_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='next_service',
        ),
    ]
