# Generated by Django 3.0.9 on 2020-08-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='DateTime on wich the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='DateTime on wich the object was last modiefed', verbose_name='modified at')),
                ('is_active', models.BooleanField(default=True, help_text='used fot disabiling when the service was done', verbose_name='active status')),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='DateTime on wich the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='DateTime on wich the object was last modiefed', verbose_name='modified at')),
                ('name', models.CharField(max_length=140, verbose_name='services name')),
                ('about', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='used fot disabiling when the service was done', verbose_name='active status')),
                ('taked_at', models.DateTimeField()),
                ('service_date', models.DateTimeField()),
                ('order_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.Machine')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
