# Generated by Django 3.1 on 2020-08-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='owner_machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='Propietario de la Máquina'),
        ),
        migrations.AddField(
            model_name='comment',
            name='made_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='made_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service'),
        ),
    ]
