# Generated by Django 3.1 on 2020-08-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200826_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='owner_machine',
        ),
    ]
