# Generated by Django 3.0.9 on 2020-08-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200805_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='taked_at',
            field=models.DateTimeField(null=True),
        ),
    ]
