# Generated by Django 3.1 on 2020-08-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200805_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='used fot disabiling when the service was done', verbose_name='Es Activo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='about',
            field=models.TextField(blank=True, verbose_name='Acerca del service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='used fot disabiling when the service was done', verbose_name='Es usuario activo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Nombre Del Servicio'),
        ),
    ]
