# Generated by Django 3.1 on 2020-08-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_auto_20200820_1632'),
        ('users', '0003_auto_20200820_1632'),
        ('services', '0004_auto_20200820_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='order_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machine', verbose_name='Servició ordenado en la máquina'),
        ),
        migrations.AlterField(
            model_name='service',
            name='owner_machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='Propietario de la Máquina'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_date',
            field=models.DateTimeField(verbose_name='Fecha del servicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='taked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tomado en'),
        ),
    ]
